## Data exploration

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
jd_df = pd.read_csv('datasets/job_description.csv')

In [20]:
jd_df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

In [21]:
keep_columns = ['job_title', 'job_description', 'location']

In [22]:
jd_df = jd_df[keep_columns]

In [23]:
jd_df.head()

,job_title,job_description,location
0,IT Support Technician Job in Madison,TeamSoft is seeing an IT Support Specialist to...,"Madison, WI 53702"
1,Business Reporter/Editor Job in Madison,The Wisconsin State Journal is seeking a flexi...,"Madison, WI 53708"
2,Johnson & Johnson Family of Companies Job Appl...,Report this job About the Job DePuy Synthes Co...,DePuy Synthes Companies is a member of Johnson...
3,Engineer - Quality Job in Dixon,Why Join Altec? If you’re considering a career...,"Dixon, CA"
4,Shift Supervisor - Part-Time Job in Camphill,Position ID# 76162 # Positions 1 State CT C...,"Camphill, PA"

In [24]:
jd_df.to_csv('datasets/cleaned_job_description.csv', index=False)